/* Auto-generated by Ghidra ExportDecompiledC script */
/* Program : hello_esp32p4.elf */
/* Language: RISCV:LE:32:ESP32-P4 */
/* Fixes applied:
 *   Fix 1 — gp = 0x<hex>; / gp = &__global_pointer_; lines stripped
 *   Fix 2 — void return promoted to undefined4 (caller-driven)
 *   Fix 3 — bare return; -> return <last-local>; in promoted functions
 *           (ClangAST RETURN Varnode slice, text-scan fallback)
 * Fix 4 — return variable resolved via backward PcodeOp.RETURN Varnode slice
 *           (tracks a0 through COPY/CAST/INT_ZEXT chains, depth <= 6)
 * Semantic enrichments:
 *   Sprint 1  — sorted output, typed sig, callers, ROM extern
 *   Sprint 7  — smart bare-return (backwards local-var scan)
 *   Sprint 8  — peripheral access annotation, region sections
 *   Sprint 11 — string constants extracted from DAT_ references
 *   P5        — ClangAST bare-return fallback (getCCodeMarkup walk)
 *   Sprint 24 — extern declarations for referenced global symbols
 *   Sprint 25 — inline struct/enum/union/typedef definitions
 * Compile with:
 *   riscv32-esp-elf-gcc -march=rv32imafc_zicsr_zifencei \
 *     -mabi=ilp32f -O0 -include ghidra_types.h -c firmware_decompiled.c
 */
#include "ghidra_types.h"

/* ─── Type definitions (Sprint 25: struct/enum/union from DataTypeManager) ─── */
typedef struct ListItem_t ListItem_t;
typedef struct List_t List_t;
typedef struct QueueDefinition QueueDefinition;
typedef struct StaticQueue_t StaticQueue_t;
typedef struct StaticTask_t StaticTask_t;
typedef struct tskTaskControlBlock tskTaskControlBlock;

typedef void * EventGroupHandle_t;

struct ListItem_t {
    unsigned int xItemValue;
    void *pxNext;
    void *pxPrevious;
    void *pvOwner;
    void *pvContainer;
};

struct List_t {
    unsigned int uxNumberOfItems;
    ListItem_t *pxIndex;
    ListItem_t xListEnd;
};

typedef void * MessageBufferHandle_t;

struct QueueDefinition {
    unsigned char *pcHead;
    unsigned char *pcWriteTo;
    unsigned char *pcReadFrom_or_semCount;
    List_t xTasksWaitingToSend;
    List_t xTasksWaitingToReceive;
    unsigned int uxMessagesWaiting;
    unsigned int uxLength;
    unsigned int uxItemSize;
    unsigned char cRxLock;
    unsigned char cTxLock;
};

typedef void * QueueHandle_t;

typedef void * SemaphoreHandle_t;

struct StaticQueue_t {
    unsigned char ucDummy[82];
};

struct StaticTask_t {
    unsigned char ucDummy[92];
};

typedef void * StreamBufferHandle_t;

typedef void * TaskHandle_t;

struct tskTaskControlBlock {
    void *pxTopOfStack;
    ListItem_t xStateListItem;
    ListItem_t xEventListItem;
    unsigned int uxPriority;
    void *pxStack;
    char pcTaskName[16];
    unsigned int xCoreID;
    void *pxEndOfStack;
    unsigned int uxTCBNumber;
    unsigned int uxTaskNumber;
    unsigned int uxBasePriority;
    unsigned int uxMutexesHeld;
};

typedef tskTaskControlBlock TCB_t;

typedef void * TimerHandle_t;

/* ─── Global variables referenced in decompiled bodies ─── */
extern volatile unsigned int g_result;


/* ╔══════════════════════════════════════════════════════╗
 * ║  SECTION: .text                                     ║
 * ║  range:   0x40000000 – 0x40000089                  ║
 * ╚══════════════════════════════════════════════════════╝
 */
/* ─── hello_world @ 0xram:40000000
 * region  : .text
 * typed   : undefined hello_world(void)
 * callers : _start
 */

void hello_world(void)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  uint uVar6;
  uint uVar7;
  
  uVar7 = 0;
  uVar6 = 0xffffffff;
  iVar1 = 1;
  uVar3 = 0;
  while( true ) {
    uVar6 = uVar6 ^ uVar3 << 0x18;
    iVar4 = 8;
    do {
      if ((int)uVar6 < 0) {
        uVar6 = uVar6 << 1 ^ 0x4c11db7;
      }
      else {
        uVar6 = uVar6 << 1;
      }
      iVar4 = iVar4 + -1;
    } while (iVar4 != 0);
    uVar6 = uVar6 ^ (uVar3 >> 8) << 0x18;
    iVar4 = 8;
    do {
      if ((int)uVar6 < 0) {
        uVar6 = uVar6 << 1 ^ 0x4c11db7;
      }
      else {
        uVar6 = uVar6 << 1;
      }
      iVar4 = iVar4 + -1;
    } while (iVar4 != 0);
    uVar7 = uVar7 + 1;
    if (uVar7 == 10) break;
    iVar1 = iVar1 + 1;
    uVar3 = uVar7;
    if (1 < uVar7) {
      iVar4 = 2;
      uVar3 = 1;
      uVar5 = 0;
      do {
        uVar2 = uVar3;
        uVar3 = uVar2 + uVar5;
        iVar4 = iVar4 + 1;
        uVar5 = uVar2;
      } while (iVar1 != iVar4);
    }
  }
  g_result = ~uVar6;
  return;
}

/* ─── _start @ 0xram:40000082
 * region  : .text
 * typed   : undefined _start(void)
 * callers : (none — possible root / ISR)
 */

void _start(void)

{
  hello_world();
  do {
                    /* WARNING: Do nothing block with infinite loop */
  } while( true );
}

