/* SPDX-License-Identifier: Apache-2.0
 * ESP32-P4 decompiler plugin — Dragon curve (regular paper folding) fixture.
 *
 * The dragon curve sequence (also called the regular paper folding sequence)
 * is generated by repeatedly folding a strip of paper in half.
 *
 * Formula (1-indexed): for term n, strip the trailing binary zeros
 * (i.e., divide by 2 until odd), giving m. Then divide m by 2 once more
 * to get q. If q is even (or q==0), the term is 1; otherwise it is 0.
 *
 * Equivalently: a(n) = floor((n / 2^(v2(n)+1))) mod 2 == 0 ? 1 : 0
 * where v2(n) = 2-adic valuation of n.
 *
 * First 32 terms (1-indexed):
 *   1,1,0,1,1,0,0,1,1,1,0,0,1,0,0,1,
 *   1,1,0,1,1,0,0,0,1,1,0,0,1,0,0,1
 *
 * Test: count 1s and XOR of 1-based positions with value 1.
 *   count_ones = 17 = 0x11
 *   xor_pos    = 40 = 0x28
 *   n_terms    = 32 = 0x20
 *
 * g_result = (32<<16)|(17<<8)|40 = 0x00201128
 * Bytes: 0x20, 0x11, 0x28 — all distinct and non-zero.
 *
 * Distinctive decompiler idioms:
 *   1. Strip trailing zeros: while (n % 2 == 0) { n /= 2; }
 *   2. Advance one more step: n /= 2; then check (n % 2 == 0)
 *   3. Accumulate 1-based position XOR only for matching values
 */
#include <stdint.h>

volatile uint32_t g_result;

#define DC_N 32u

/* Compute the n-th term (1-indexed) of the dragon curve sequence. */
static uint32_t dragon_term(uint32_t n)
{
    /* Strip all trailing zeros (2-adic valuation) */
    while ((n & 1u) == 0u) {
        n >>= 1;
    }
    /* Advance one more position */
    n >>= 1;
    /* If n is even (including 0), return 1; else return 0 */
    return ((n & 1u) == 0u) ? 1u : 0u;
}

void test_dragon_curve(void)
{
    uint32_t count_ones = 0u;
    uint32_t xor_pos    = 0u;
    uint32_t i;
    for (i = 1u; i <= DC_N; i++) {
        uint32_t v = dragon_term(i);
        if (v == 1u) {
            count_ones++;
            xor_pos ^= (i & 0xFFu);
        }
    }

    /* count_ones=17=0x11, xor_pos=40=0x28
     * g_result = (32<<16)|(17<<8)|40 = 0x00201128 */
    g_result = (DC_N << 16) | (count_ones << 8) | (xor_pos & 0xFFu);
}

__attribute__((noreturn)) void _start(void)
{
    test_dragon_curve();
    for (;;);
}
