/* SPDX-License-Identifier: Apache-2.0
 * ESP32-P4 decompiler plugin — Lucky Numbers Sieve fixture.
 *
 * Lucky numbers are generated by a sieve process:
 *   Start with all positive odd integers: 1,3,5,7,9,11,13,15,17,...
 *   Second value is 3: delete every 3rd element -> 1,3,7,9,13,15,19,21,25,...
 *   Next value is 7: delete every 7th element -> 1,3,7,9,13,15,21,25,...
 *   Continue sieving by successive lucky numbers.
 *
 * Distinctive decompiler idioms:
 *   1. Start with odd numbers array (step-2 initialization)
 *   2. Outer loop over lucky[k]: sieve[i] entries step=lucky[k]
 *   3. Element removal via array compaction (shift-left loop)
 *   4. Count and last-element extraction for result encoding
 *
 * Test: Lucky numbers up to 50.
 *   Lucky numbers <= 50: 1,3,7,9,13,15,21,25,31,33,37,43,49 => 13 numbers.
 *   Last lucky <= 50: 49, 49 & 0xFF = 49 = 0x31.
 *   checksum = (13 + 49) & 0xFF = 62 = 0x3E.
 *   g_result = (13<<16)|(49<<8)|62 = 0x0D313E
 */
#include <stdint.h>

volatile uint32_t g_result;

#define LUCKY_MAX 60
static uint32_t lucky_arr[LUCKY_MAX];
static uint32_t lucky_sz;

void test_lucky_numbers_sieve(void)
{
    /* Initialize with odd numbers 1,3,5,...,<2*LUCKY_MAX-1> */
    lucky_sz = 0;
    for (uint32_t i = 1; lucky_sz < (uint32_t)LUCKY_MAX; i += 2u) {
        lucky_arr[lucky_sz++] = i;
    }

    /* Sieve: for each lucky[k] starting at k=1, remove every lucky[k]-th element */
    uint32_t k = 1;
    while (k < lucky_sz) {
        uint32_t step = lucky_arr[k];
        if (step > lucky_sz) break;
        /* Remove every step-th element (1-based indexing, so index step-1, 2*step-1, ...) */
        uint32_t new_sz = 0;
        for (uint32_t i = 0; i < lucky_sz; i++) {
            /* Keep element if (i+1) is not divisible by step */
            if ((i + 1u) % step != 0u) {
                lucky_arr[new_sz++] = lucky_arr[i];
            }
        }
        lucky_sz = new_sz;
        k++;
    }

    /* Count and find last lucky number <= 50 */
    uint32_t count = 0;
    uint32_t last  = 0;
    for (uint32_t i = 0; i < lucky_sz; i++) {
        if (lucky_arr[i] <= 50u) {
            count++;
            last = lucky_arr[i];
        }
    }

    uint32_t checksum = (count + last) & 0xFFu;
    g_result = (count << 16) | ((last & 0xFFu) << 8) | checksum;
}

__attribute__((noreturn)) void _start(void)
{
    test_lucky_numbers_sieve();
    for (;;);
}
