/* SPDX-License-Identifier: Apache-2.0
 *
 * ESP32-P4 Ghidra Plugin
 * Copyright 2026 Alexander Salas Bastidas <ajsb85@firechip.dev>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Exports decompiled C for every function in the current program.
//
// The output file is user-selectable via a save dialog; it defaults to
// <program_name>.c in the user's home directory.
//
// To recompile the output add ghidra_types.h (from tools/) with
// typedefs for undefined, undefined4, uint, ulong, etc.
//
// Usage: Script Manager → ESP32-P4 → Export Decompiled C
//
// @category ESP32-P4
// @menupath Analysis.ESP32-P4.Export Decompiled C

import ghidra.app.decompiler.*;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.*;

import java.io.*;

public class ExportDecompiledC extends GhidraScript {

    private static final int DECOMPILE_TIMEOUT_SECS = 30;

    @Override
    public void run() throws Exception {
        String defaultName = currentProgram.getName().replaceAll("[^\\w.-]", "_") + ".c";
        File outFile = askFile("Save decompiled C to", "Save");
        if (outFile == null) {
            File home = new File(System.getProperty("user.home"));
            outFile = new File(home, defaultName);
            println("No file chosen — writing to " + outFile.getAbsolutePath());
        }

        DecompInterface decompiler = new DecompInterface();
        DecompileOptions opts = new DecompileOptions();
        decompiler.setOptions(opts);
        decompiler.toggleSyntaxTree(true);
        decompiler.toggleCCode(true);

        if (!decompiler.openProgram(currentProgram)) {
            printerr("Decompiler failed to open program: "
                    + decompiler.getLastMessage());
            return;
        }

        int exported = 0;
        int failed   = 0;

        try (PrintWriter pw = new PrintWriter(new FileWriter(outFile))) {
            pw.println("/* Auto-generated by Ghidra ExportDecompiledC script */");
            pw.println("/* Program : " + currentProgram.getName()  + " */");
            pw.println("/* Language: " + currentProgram.getLanguageID() + " */");
            pw.println("/*");
            pw.println(" * Compile with:");
            pw.println(" *   riscv32-esp-elf-gcc -march=rv32imafc_zicsr_zifencei \\");
            pw.println(" *     -mabi=ilp32f -O0 -nostdlib -nostartfiles \\");
            pw.println(" *     -include ghidra_types.h -c " + outFile.getName());
            pw.println(" */");
            pw.println();

            FunctionIterator it =
                    currentProgram.getListing().getFunctions(true);

            while (it.hasNext()) {
                monitor.checkCancelled();
                Function fn = it.next();

                pw.printf("/* --- %s @ %s --- */%n",
                        fn.getName(), fn.getEntryPoint());

                DecompileResults res =
                        decompiler.decompileFunction(fn, DECOMPILE_TIMEOUT_SECS, monitor);

                if (res != null && res.decompileCompleted()) {
                    DecompiledFunction df = res.getDecompiledFunction();
                    if (df != null) {
                        pw.println(df.getC());
                        exported++;
                    } else {
                        pw.println("/* decompile returned null */");
                        failed++;
                    }
                } else {
                    String msg = (res != null) ? res.getErrorMessage() : "null";
                    pw.println("/* decompile failed: " + msg + " */");
                    failed++;
                }
                pw.println();
            }
        } finally {
            decompiler.dispose();
        }

        println(String.format(
            "Export complete: %d functions written, %d failed → %s",
            exported, failed, outFile.getAbsolutePath()));

        if (failed > 0)
            printerr(failed + " function(s) could not be decompiled — "
                   + "check output for /* decompile failed */ markers.");
    }
}
