// SPDX-License-Identifier: Apache-2.0
// @category ESP32-P4
// @menupath Analysis.ESP32-P4.Export Global Declarations
// @description Scans all decompiled function bodies for global data references
//              and emits extern/volatile declarations to a .h file.

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.*;
import ghidra.program.model.data.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.mem.*;
import ghidra.program.model.symbol.*;
import ghidra.app.decompiler.*;

import java.io.*;
import java.util.*;
import java.util.regex.*;

public class ExportGlobalDecls extends GhidraScript {

    // Matches DAT_XXXXXXXX or FUN_XXXXXXXX from decompiled output
    private static final Pattern ADDR_REF =
        Pattern.compile("\\b(?:DAT|FUN)_([0-9A-Fa-f]{8})\\b");

    // Peripheral range: address range where volatile is warranted
    private static final long PERIPH_BASE = 0x40000000L;
    private static final long PERIPH_END  = 0x5FFFFFFFL;

    @Override
    public void run() throws Exception {
        // Determine output file
        String[] args = getScriptArgs();
        File outFile;
        if (args != null && args.length > 0 && !args[0].isEmpty()) {
            outFile = new File(args[0]);
        } else {
            outFile = askFile("Save global declarations to", "Save");
        }

        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);
        decomp.setSimplificationStyle("decompile");

        Listing        listing = currentProgram.getListing();
        Memory         memory  = currentProgram.getMemory();
        SymbolTable    symtab  = currentProgram.getSymbolTable();
        AddressFactory af      = currentProgram.getAddressFactory();

        // Collect all unique data-reference target addresses from all functions
        TreeMap<Long, String> globals = new TreeMap<>();  // addr → C declaration

        FunctionIterator funcs = listing.getFunctions(true);
        int processed = 0, total = 0;
        while (funcs.hasNext() && !monitor.isCancelled()) {
            Function fn = funcs.next();
            total++;
            DecompileResults res = decomp.decompileFunction(fn, 30, monitor);
            if (res == null || !res.decompileCompleted()) continue;
            String raw = res.getDecompiledFunction().getC();
            if (raw == null) continue;
            processed++;

            Matcher m = ADDR_REF.matcher(raw);
            while (m.find()) {
                long addr = Long.parseUnsignedLong(m.group(1), 16);
                if (globals.containsKey(addr)) continue;

                Address ghidraAddr;
                try {
                    ghidraAddr = af.getDefaultAddressSpace().getAddress(addr);
                } catch (Exception e) {
                    continue;
                }

                // Skip if in executable memory (it's a function reference, not data)
                MemoryBlock blk = memory.getBlock(ghidraAddr);
                if (blk == null) continue;
                if (blk.isExecute()) {
                    // Still emit extern prototype if we have a symbol
                    Symbol[] syms = symtab.getSymbols(ghidraAddr);
                    if (syms.length > 0 && !syms[0].getName().startsWith("FUN_")) {
                        globals.put(addr, "extern void " + syms[0].getName() + "(void);");
                    }
                    continue;
                }

                String decl = buildDeclaration(addr, ghidraAddr, listing, symtab);
                globals.put(addr, decl);
            }
            monitor.setProgress(total);
        }
        decomp.dispose();

        // Write output
        try (PrintWriter pw = new PrintWriter(new FileWriter(outFile))) {
            pw.println("/* Auto-generated by ExportGlobalDecls.java — do not edit manually */");
            pw.println("/* Re-run after re-analysis to pick up renamed or retyped symbols. */");
            pw.println("#pragma once");
            pw.println("#include \"ghidra_types.h\"");
            pw.println();

            String prevRegion = null;
            for (Map.Entry<Long, String> e : globals.entrySet()) {
                long   addr = e.getKey();
                String decl = e.getValue();

                // Section header when region changes
                Address ghidraAddr;
                try { ghidraAddr = currentProgram.getAddressFactory()
                                       .getDefaultAddressSpace().getAddress(addr); }
                catch (Exception ex) { pw.println(decl); continue; }
                MemoryBlock blk = currentProgram.getMemory().getBlock(ghidraAddr);
                String region = (blk != null) ? blk.getName() : "unknown";
                if (!region.equals(prevRegion)) {
                    pw.println();
                    pw.println("/* ── " + region + " ──────────────────────────── */");
                    prevRegion = region;
                }
                pw.println(decl);
            }
            pw.println();
        }

        println("ExportGlobalDecls: " + globals.size() + " declarations from "
                + processed + "/" + total + " functions → " + outFile.getPath());
    }

    // Build a C extern declaration for a data address
    private String buildDeclaration(long rawAddr, Address addr,
                                    Listing listing, SymbolTable symtab) {
        // Determine variable name
        String name = "DAT_" + String.format("%08X", rawAddr).toLowerCase();
        Symbol[] syms = symtab.getSymbols(addr);
        if (syms.length > 0 && !syms[0].getName().startsWith("DAT_")) {
            name = syms[0].getName();
        }

        // Determine C type from Ghidra listing
        String cType = ghidraTypeToCType(listing, addr);

        // Add volatile for peripheral-mapped addresses
        boolean isPeripheral = (rawAddr >= PERIPH_BASE && rawAddr <= PERIPH_END);
        String volatileStr = isPeripheral ? "volatile " : "";

        return "extern " + volatileStr + cType + " " + name + ";";
    }

    private String ghidraTypeToCType(Listing listing, Address addr) {
        Data data = listing.getDataAt(addr);
        if (data == null) return "uint32_t";

        DataType dt = data.getDataType();
        if (dt == null) return "uint32_t";

        String dtName = dt.getName();

        // String types
        if (dt instanceof StringDataType
                || dt instanceof TerminatedStringDataType
                || dt instanceof UnicodeDataType) {
            return "char[]";
        }
        // Arrays
        if (dt instanceof ArrayDataType) {
            ArrayDataType adt = (ArrayDataType) dt;
            String elemType = ghidraBaseTypeName(adt.getDataType());
            return elemType + "[" + adt.getNumElements() + "]";
        }
        // Pointer
        if (dt instanceof Pointer) {
            Pointer ptr = (Pointer) dt;
            DataType base = ptr.getDataType();
            String baseName = (base != null) ? ghidraBaseTypeName(base) : "void";
            return baseName + " *";
        }
        // Struct/Enum — use the Ghidra type name as-is
        if (dt instanceof Structure || dt instanceof ghidra.program.model.data.Enum) {
            return dtName;
        }
        // Sized undefineds / scalars
        return ghidraBaseTypeName(dt);
    }

    private String ghidraBaseTypeName(DataType dt) {
        if (dt == null) return "uint32_t";
        String name = dt.getName();
        switch (name) {
            case "undefined1": case "byte":  case "uchar":  return "uint8_t";
            case "undefined2": case "word":  case "ushort": return "uint16_t";
            case "undefined4": case "dword": case "uint":   return "uint32_t";
            case "undefined8": case "qword": case "ulong":  return "uint64_t";
            case "char":  return "char";
            case "short": return "int16_t";
            case "int":   return "int32_t";
            case "long":  return "int32_t";
            case "float": return "float";
            case "double":return "double";
            default:
                if (name.startsWith("undefined")) return "uint8_t";
                return name;  // user-defined type: keep as-is
        }
    }
}
